language: java # setting the language enables Travis to create a Java Docker container to execure further steps
jdk: oraclejdk9 # Version of Java
dist: trusty # This is required if maven dependencies are on HTTPS
sudo: required
install: true # 'true' makes the install script to execute nothing.
script: cd project-details-app && mvn clean install
services:
  - docker # Docker container will install Docker
after_success:
  - docker build -t hunaidee/full-stack -f ./Dockerfile-travis .
  - docker login -u $DOCKER_USER_NAME -p $DOCKER_HUB_PASSWORD
  - docker tag hunaidee/full-stack:latest hunaidee/full-stack:latest
  - docker push hunaidee/full-stack
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --no-include-email --region us-east-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker tag hunaidee/full-stack:latest 550444087576.dkr.ecr.us-east-2.amazonaws.com/full-stack-aws:latest
  - docker push 550444087576.dkr.ecr.us-east-2.amazonaws.com/full-stack-aws:latest

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "full-stack-aws"
  env: "FullStackAws-env"
  bucket_name: "elasticbeanstalk-us-east-2-550444087576"
  bucket_path: "full-stack-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
