language: java
jdk: oraclejdk9
dist: trusty
sudo: required
install: true
script: cd project-details-app && mvn clean install
services:
  - docker
after_success:
  - docker build -t hunaidee/full-stack -f ./Dockerfile-travis .
  - docker login -u $DOCKER_USER_NAME -p $DOCKER_HUB_PASSWORD
  - docker tag hunaidee/full-stack:first hunaidee/full-stack:first
  - docker push hunaidee/full-stack
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "full-stack-aws"
  env: "FullStackAws-env"
  bucket_name: "elasticbeanstalk-us-east-2-550444087576"
  bucket_path: "full-stack-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY