language: java
jdk: oraclejdk9
dist: trusty
sudo: required
install: true
script: cd project-details-app && mvn clean install
services:
  - docker
before_install:
  - docker build -t hunaidspring -f ./project-details-app/Dockerfile .