FROM openjdk
RUN mkdir /usr/src/myapp
COPY ./home/travis/build/chanabasappa-prog/full-stack/project-details-app/target/project-details-app-0.0.1-SNAPSHOT.jar /usr/src/myapp/app.jar
ENTRYPOINT ["java","-jar","/usr/src/myapp/app.jar"]