FROM openjdk
RUN mkdir /usr/src/myapp
COPY $HOME/.m2/repository/com/application/project-details-app/0.0.1-SNAPSHOT/project-details-app-0.0.1-SNAPSHOT.jar /usr/src/myapp/app.jar
ENTRYPOINT ["java","-jar","/usr/src/myapp/app.jar"]